Online_Marketplace/urls.py

from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls')),
    url(r'^bike/', include('bike.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bike/urls.py
from django.conf.urls import url
from . import views

app_name = 'bike'

#
urlpatterns = [
    url(r'^$', views.bike, name='index'),

    #/bike/2/
    url(r'^(?P<pk>[0-9]+)/$', views.details, name='details'),

    #/bike/add/
    url(r'^add/$', views.BikeInsert.as_view(), name='bike-add'),

    url(r'^insert/$', views.BikeInsert.as_view(), name='bike-insert'),
]

home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    url(r'^login/$', views.UserLogin.as_view(), name='login'),

    url(r'^logout/$', views.logout_user, name='user-logout'),

    url(r'^userinfo/$', views.UserInfoView.as_view(), name='user-info'),

    url(r'^trial/$', views.register, name='trial'),
]

bike/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class TwoWheeler(models.Model):
    Model_name = models.CharField(max_length=200)
    Company_name = models.CharField(max_length=100)
    Model_Info = models.CharField(max_length=1000)
    Price_before = models.IntegerField(default=0)
    Price_after = models.IntegerField(default=0)
    Model_img = models.FileField()

    def get_absolute_url(self):
        return reverse('bike:details', kwargs={'pk': self.pk})

    def __str__(self):
        return self.Model_name + '  -  ' + self.Company_name

home/models.py
from django.db import models

Cities = (('p', 'Pune'), ('b', 'Bangalore'), ('m', 'Mumbai'), )


# Create your models here.
class UserInfo(models.Model):
    name = models.CharField(max_length=100)
    city = models.CharField(max_length=50, choices=Cities)

    def __str__(self):
        return self.name + '  ' + self.city

home/forms.py
from django.contrib.auth.models import User
from .models import UserInfo
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import models


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ['name', 'city']


class TrialForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'password1', 'password2', 'email']

    def save(self, commit=True):
        user = super(TrialForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        if commit:
            user.save()

        return user

bike/views.py
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import render, redirect
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView
from .models import TwoWheeler


# Create your views here.
def bike(request):
    bike_all = TwoWheeler.objects.all()
    con = {
        'bike_all': bike_all,
    }
    return render(request, "bike/first.html", con)


def details(request, pk):
    try:
        x = TwoWheeler.objects.get(pk=pk)
    except TwoWheeler.DoesNotExist:
        raise Http404("Vehicle Not Found")
    con = {
        'x': x,
    }
    return render(request, "bike/details.html", con)


class BikeInsert(CreateView):
    model = TwoWheeler
    fields = ['Model_name', 'Company_name', 'Model_Info', 'Model_img', 'Price_before', 'Price_after']

home/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.http import Http404
from bike.models import TwoWheeler
from home.models import UserInfo
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from .forms import UserForm, LoginForm, UserInfoForm, TrialForm
from django.forms import ModelForm


# TEST

class UserInfoView(View):
    form_class = UserInfoForm
    template_name = 'home/login_page.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})


# Create your views here.
def index(request):
    bike_all = TwoWheeler.objects.all()
    cont = {
        'bike_all': bike_all,
    }
    return render(request, 'home/homepage.html', cont)


class UserFormView(View):
    form_class = UserForm
    template_name = 'home/register.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('home:index')

        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})


class UserLogin(View):
    form_class = LoginForm
    template_name = 'home/login_page.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home:index')
        else:
            form = self.form_class(None)
            return render(request, self.template_name, {'form': form})


def logout_user(request):

    logout(request)
    return redirect('home:index')


class TrialView(View):
    form_class = TrialForm
    template_name = 'home/register.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home:index')
        else:
            return redirect('bike:index')


def register(request):
    if request.method == 'POST':
        form = TrialForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home:index')
        else:
            return redirect('bike:index')
    else:
        form = TrialForm(None)
        return render(request, 'home/trial.html', {'form': form})

bike/templates/bike/details.html
{% extends 'home/base.html' %}

{% block title %}Bike Details{% endblock %}

{% block body %}
<h1>{{ x.Model_name }}</h1>
<h1>{{ x.Company_name }}</h1>
{% endblock %}

bike/templates/bike/first.html
{% extends 'home/base.html' %}

{% block title %}Bikes{% endblock %}

{% block body %}
{% if bike_all %}
<h1>WELCOME Bikes!!!!!!!!!</h1>

<u1>
    {% for all in bike_all %}
    <li>{{ all.Model_name }}</li>
    {% endfor %}
</u1>
{% else %}
    <h3>ADD BIKES</h3>
{% endif %}
{% endblock %}

bike/templates/bike/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ fields.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

bike/templates/bike/twowheeler_form.html
{% extends 'home/base.html' %}



{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'bike/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">SUBMIT</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

home/templates/home/base.html
<!DOCTYPE html>
<html class="no-js" lang="en">

<header>
    <title>{% block title %}ONLINE MARKETPLACE{% endblock %}</title>
    {% load staticfiles %}
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,800">
    <link href="https://fonts.googleapis.com/css?family=Text+Me+One|Titillium+Web:700" rel="stylesheet">
    <link rel='stylesheet' href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}">
</header>

<body>
    {% load staticfiles %}
    <script src="{% static 'home/js/jquery.min.js' %}"></script>
    <script src="https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="{% static 'home/js/popper.min.js' %}"></script>
    <script src="{% static 'home/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'home/js/test.js' %}"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <header>
        <nav class="navbar  navbar-expand-lg navbar-light top-navbar" data-toggle="sticky-onscroll">
            <div class="container-fluid mx-5">
                <a class="navbar-brand" href="{% url 'home:index' %}">
                    <h1 style="font-size: 3rem">ONLINE MARKETPLACE</h1>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse justify-content-end" style="margin-bottom:0.8rem" id="navbarSupportedContent">
                    <ul class="navbar-nav pull-right">
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'home:index' %}">HOME</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="{% url 'bike:index' %}" id="navbarDropdown" role="button" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                                BUY
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#">MOPEDS</a>
                                <a class="dropdown-item" href="#">BIKES</a>
                                <a class="dropdown-item" href="#">SCOOTERS</a>
                                <a class="dropdown-item" href="#">BICYCLES</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'bike:bike-add' %}">SELL</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">ABOUT</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">CONTACT</a>
                        </li>

                        {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home:login' %}">LOGIN</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home:user-logout' %}">LOGOUT</a>
                        </li>
                        {% endif %}

                    </ul>
                    <div class="input-group col-2">
                        <input class="form-control py-2 border-right-0 border" type="search" value="search" id="example-search-input">
                        <span class="input-group-append">
                            <div class="input-group-text bg-transparent"><i class="fa fa-search"></i></div>
                        </span>
                    </div>


                </div>
            </div>
        </nav>
        </header>
{% block body %}
{% endblock %}
</body>

<footer class="page-footer font-small blue pt-4">

    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3"><a href="#"> Contact Us </a> | <a href="#">Support </a> | © 2018
        Copyright:
        <a href="#"> onlinemarketplace.com</a>
    </div>
    <!-- Copyright -->

    </footer>

</html>

home/templates/home/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ fields.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

home/templates/home/homepage.html
{% extends 'home/base.html' %}

{% block body %}
    <div id="carouselExampleFade" class="carousel slide" data-interval="2000" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100 img-responsive" {% load static %} src= {% static "home/assets/hornet1.jpg" %} alt="First slide">
                    <div class="carousel-caption d-none d-md-block">
                        <h1 style="font-family:Titillium Web;font-size: 5rem">HORNET WEEKENDS</h1>
                        <p style="font-family:Titillium Web;font-size: 3rem">Get 20% off on all hornet models on
                            weekends by applying code HORNET20</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100 img-responsive" {% load static %} src={% static "home/assets/gixer.jpg" %} alt="Second slide">
                    <div class="carousel-caption d-none d-md-block">
                        <h1 style="font-family:Titillium Web;font-size: 5rem">GIXER DHAMAKA</h1>
                        <p style="font-family:Titillium Web;font-size: 3rem">Flat Rs 5000 Off on all Gixer models.
                            Hurry up offer valid only till 12th December 2018</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100 img-responsive" {% load static %} src={% static "home/assets/pulsar.jpg" %} alt="Third slide">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

    <div class="container-fluid">

        <div class="row mt-sm-5 mt-md-5 ml-md-3 mr-md-3">
        {% for bike in bike_all %}
         <div class="col-sm-12 col-md-3 mt-md-0 ">
                <div class="card" style="width: 24rem;">
                    <a href="{% url 'bike:details' bike.id %}"><img class="card-img-top" src="{{ bike.Model_img.url }}" alt="Card image cap"></a>
                    <div class="card-body">
                        <h5 class="card-title text-center">{{ bike.Model_name }} </h5>
                        <p class="card-text">{{ bike.Model_Info }}</p>
                        <p class="beforetext">BEFORE : <del>{{ bike.Price_before }}</del></p>
                        <p class="nowtext">NOW : <span class="pricetext">{{ bike.Price_after }}</span></p>
                        <a href="#" class="btn btn-primary aligner">Buy Now</a>
                    </div>
                </div>
         </div>
        {% endfor %}
         </div>

    </div>
{% endblock %}

home/templates/home/login_page.html
{% extends 'home/base.html' %}

{% block title %}Login{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'home/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">SUBMIT</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

home/templates/home/register.html
{% extends 'home/base.html' %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'home/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">SUBMIT</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

home/templates/home/trial.html
{% extends 'home/base.html' %}

{% block title %}Register{% endblock %}

{% block body %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">SUBMIT</button>
</form>

{% endblock %}

home/templates/home/userinfo_form.html
{% extends 'home/base.html' %}

{% block title %}User Info{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'home/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">SUBMIT</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}